apiVersion: apps/v1
kind: Deployment

metadata:
  name: federator-server

spec:
  template:
    spec:
      containers:
        - name: federator-server
          image: 127214183387.dkr.ecr.eu-west-2.amazonaws.com/federator-server:latest
