apiVersion: apps/v1
kind: Deployment

metadata:
  name: federator-client

spec:
  template:
    spec:
      containers:
        - name: federator-client
          image: 127214183387.dkr.ecr.eu-west-2.amazonaws.com/federator-client:latest
