apiVersion: secrets-store-csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: ianode-access-db-password

spec:
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:eu-west-2:127214183387:secret:ndtp-testing-docdb-cluster-root-password-aEDrjA"
        objectType: "secretsmanager"
        objectAlias: "password"
