apiVersion: apps/v1
kind: Deployment

metadata:
  name: ianode-access-api

spec:
  template:
    spec:
      containers:
        - name: ianode-access-api
          image: 127214183387.dkr.ecr.eu-west-2.amazonaws.com/ianode-access:latest
