apiVersion: v1
kind: Namespace
metadata:
  name: ndtp
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-github.yaml convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: secure-agent-graph-container
  name: secure-agent-graph-container
  namespace: ndtp
spec:
  ports:
  - name: "3030"
    port: 3030
    targetPort: 3030
  selector:
    io.kompose.service: secure-agent-graph-container
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: secure-agent-graph-container-claim0
  name: secure-agent-graph-container-claim0
  namespace: ndtp
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: secure-agent-graph-container-claim1
  name: secure-agent-graph-container-claim1
  namespace: ndtp
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: secure-agent-graph-container-claim2
  name: secure-agent-graph-container-claim2
  namespace: ndtp
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-github.yaml convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: secure-agent-graph-container
  name: secure-agent-graph-container
  namespace: ndtp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: secure-agent-graph-container
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-github.yaml convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: secure-agent-graph-container
    spec:
      containers:
      - args:
        - --config
        - config/config-abac-local.ttl
        env:
        - name: JAVA_OPTIONS
          value: -Xmx2048m -Xms2048m
        - name: JWKS_URL
          value: https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_oGJ7rFJsw/.well-known/jwks.json
        - name: USER_ATTRIBUTES_URL
          value: http://access-api:8091
        image: 127214183387.dkr.ecr.eu-west-2.amazonaws.com/secure-agent-graph:latest
        name: secure-agent-graph-container
        ports:
        - containerPort: 3030
          protocol: TCP
        volumeMounts:
        - mountPath: /fuseki/logs
          name: secure-agent-graph-container-claim0
        - mountPath: /fuseki/databases
          name: secure-agent-graph-container-claim1
        - mountPath: /fuseki/config
          name: secure-agent-graph-container-claim2
      restartPolicy: Always
      volumes:
      - name: secure-agent-graph-container-claim0
        persistentVolumeClaim:
          claimName: secure-agent-graph-container-claim0
      - name: secure-agent-graph-container-claim1
        persistentVolumeClaim:
          claimName: secure-agent-graph-container-claim1
      - name: secure-agent-graph-container-claim2
        persistentVolumeClaim:
          claimName: secure-agent-graph-container-claim2
