apiVersion: v1
kind: Service

metadata:
  name: secure-agent-graph-server
  namespace: input.a.namespace

spec:
  selector:
    app.kubernetes.io/name: secure-agent-graph-server
  ports:
    - name: http
      protocol: TCP
      port: 3030
      targetPort: 3030
    - name: metrics
      protocol: TCP
      port: 9464
      targetPort: 9464
