apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeTemplates: true
    pairs:
      app: ianode-access-api
      app.kubernetes.io/name: ianode-access-api

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
