apiVersion: secrets-store-csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: ianode-access-db-password
  namespace: input.a.namespace

spec:
  provider: aws
  parameters:
    objects: |
      - objectName: input.secret.arn
        objectAlias: password
  secretObjects:
    - secretName: ianode-access-db-password
      type: Opaque
      data: 
        - objectName: "ianode-access-db-password"
          key: password
