apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  labels:
    app: ianode-access
    app.kubernetes.io/name: ianode-access
  name: ianode-access-db-password
  namespace: input.a.namespace

spec:
  provider: aws
  parameters:
    objects: |
      - objectName: input.secret.arn
        objectType: "secretsmanager"
        objectAlias: "password"
  secretObjects:
    - secretName: "ianode-access-db-password"
      type: Opaque
      data: 
        - objectName: input.secret.arn
          key: "password"
