apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-github.yaml convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: access-api
  name: access-api
spec:
  ports:
    - name: "8091"
      port: 8091
      targetPort: 8091
  selector:
    io.kompose.service: access-api
