apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: access-api
  name: access-api
  namespace: input.a.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: access-api
  template:
    metadata:
      labels:
        io.kompose.service: access-api
    spec:
      containers:
        - args:
            - "/app/wait-for.sh"
            - "$MONGO_URL"
            - "--"
            - "node"
            - "dist/index.js"
          env:
            - name: DEBUG
              value: '"true"'
            - name: DEPLOYED_DOMAIN
              value: http://localhost:3000
            - name: GROUPS_KEY
              value: cognito:groups
            - name: MONGO_COLLECTION
              value: access
            - name: MONGO_PROTOCOL
              value: mongodb
            - name: MONGO_PWD
              value: input.MONGO_PWD
            - name: MONGO_URL
              value: input.MONGO_URL
            - name: MONGO_USER
              value: input.MONGO_USER
            - name: OPENID_PROVIDER_URL
              value: input.OPENID_PROVIDER_URL
            - name: PORT
              value: "8091"
            - name: SCIM_ENABLED
              value: "true"
          image: input.image
          name: access-api-ianode
          ports:
            - containerPort: 8091
              protocol: TCP
      restartPolicy: Always
