apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: secure-agent-graph-container
  name: secure-agent-graph-container
  namespace: input.a.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: secure-agent-graph-container
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: secure-agent-graph-container
    spec:
      serviceAccountName: secure-agent-graph-sa
      containers:
          args:
            - "--config"
            - "/fuseki/config/config.ttl"
          env:
            - name: JAVA_OPTIONS
              value: -Xmx2048m -Xms2048m
            - name: JWKS_URL
              value: input.JWKS_URL
            - name: USER_ATTRIBUTES_URL
              value: http://access-api:8091
          image: input.image
          name: secure-agent-graph-container
          ports:
            - containerPort: 3030
              protocol: TCP
          volumeMounts:
            - mountPath: /fuseki/logs
              name: secure-agent-graph-container-claim0
            - mountPath: /fuseki/databases
              name: secure-agent-graph-container-claim1
            - mountPath: /fuseki/config
              name: secure-agent-graph-container-claim2
      restartPolicy: Always
      volumes:
        - name: secure-agent-graph-container-claim0
          persistentVolumeClaim:
            claimName: secure-agent-graph-container-claim0
        - name: secure-agent-graph-container-claim1
          persistentVolumeClaim:
            claimName: secure-agent-graph-container-claim1
        - name: secure-agent-graph-container-claim2
          persistentVolumeClaim:
            claimName: secure-agent-graph-container-claim2
