apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: secure-agent-graph-container
  name: secure-agent-graph-container
  namespace: input.a.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: secure-agent-graph-container
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: secure-agent-graph-container
    spec:
      serviceAccountName: secure-agent-graph-sa
      containers:
        - args:
            - --config
            - config/config-abac-local.ttl
          env:
            - name: JAVA_OPTIONS
              value: -Xmx2048m -Xms2048m
            - name: JWKS_URL
              value: https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_oGJ7rFJsw/.well-known/jwks.json
            - name: USER_ATTRIBUTES_URL
              value: http://access-api:8091
          image: 127214183387.dkr.ecr.eu-west-2.amazonaws.com/secure-agent-graph:latest
          name: secure-agent-graph-container
          ports:
            - containerPort: 3030
              protocol: TCP
          volumeMounts:
            - mountPath: /fuseki/logs
              name: secure-agent-graph-container-claim0
            - mountPath: /fuseki/databases
              name: secure-agent-graph-container-claim1
            - mountPath: /fuseki/config
              name: secure-agent-graph-container-claim2
      restartPolicy: Always
      volumes:
        - name: secure-agent-graph-container-claim0
          persistentVolumeClaim:
            claimName: secure-agent-graph-container-claim0
        - name: secure-agent-graph-container-claim1
          persistentVolumeClaim:
            claimName: secure-agent-graph-container-claim1
        - name: secure-agent-graph-container-claim2
          persistentVolumeClaim:
            claimName: secure-agent-graph-container-claim2
