apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: secure-agent-graph-container-claim2
  name: secure-agent-graph-container-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
