apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: secure-agent-graph-container
  name: secure-agent-graph-container
spec:
  ports:
    - name: "3030"
      port: 3030
      targetPort: 3030
  selector:
    io.kompose.service: secure-agent-graph-container
