apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../resources/

namespace: ndtp-testing

patches:
  - target:
      kind: Namespace
      name: input.name
    patch: |-
      - op: replace
        path: /metadata/name
        value: ndtp-testing
  - path: secure-agent-graph-container-deployment_patch.yaml
    target: 
      kind: Deployment
      name: secure-agent-graph-container
  - path: access-api-deployment_patch.yaml
    target: 
      kind: Deployment
      name: access-api
