apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../resources/

patches:
  - target:
      kind: Namespace
      name: default.change
    patch: |-
      - op: replace
        path: /metadata/name
        value: ndtp-testing
