apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

patches:
  - target:
      kind: Namespace
      name: name.override.required
    patch: |-
      - op: replace
        path: /metadata/name
        value: testing
