apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-github.yaml convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: secure-agent-graph-container
  name: secure-agent-graph-container
spec:
  ports:
    - name: "3030"
      port: 3030
      targetPort: 3030
  selector:
    io.kompose.service: secure-agent-graph-container
